openapi: 3.0.0
info:
  title: File Storage API
  version: 1.0.0
  description: API for file upload and download
paths:
  /upload:
    post:
      summary: Upload a file
      operationId: uploadFile
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: File uploaded successfully
  /download/{fileId}:
    get:
      summary: Download a file by ID
      operationId: downloadFile
      parameters:
        - name: fileId
          in: path
          description: ID of the file to download
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: File downloaded successfully
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          description: File not found
